version: "3.8"

services:
  web-api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: web-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:8080"
