version: "3.8"

services:
  pharmago-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: pharmago-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Str0ngP@ssword!
    ports:
      - "11433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  pharmago-api:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: pharmago-api
    environment:
      - ConnectionStrings__DefaultConnection=Server=pharmago-db;Database=PharmaDb;User Id=sa;Password=Str0ngP@ssword!
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80" # API available on localhost:5000
    depends_on:
      - pharmago-db
      - otlp-collector

  otlp-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otlp-collector
    ports:
      - "4317:4317"
      - "8889:8889"
    volumes:
      - ./Backend/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config=/etc/otel-collector-config.yaml"]

volumes:
  sql_data:
